config/routes.rb
Rails.application.routes.draw do
  resources :hospitalizations
  resources :treatments
  resources :appointments
  resources :diagnoses
  resources :diets
  devise_for :doctors
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  get 'pages/about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "pages#home"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :user
  belongs_to :doctor
end

app/models/diagnosis.rb
class Diagnosis < ApplicationRecord
  belongs_to :user
  belongs_to :doctor
end

app/models/diet.rb
class Diet < ApplicationRecord
  belongs_to :user
  belongs_to :doctor
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :users
  has_many :treatments
  has_many :diets
  has_many :diagnosis
  has_many :appointments
  has_many :hospitalizations 
    
end

app/models/hospitalization.rb
class Hospitalization < ApplicationRecord
	belongs_to :user
    belongs_to :doctor
end

app/models/treatment.rb
class Treatment < ApplicationRecord
  belongs_to :user
  belongs_to :doctor
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :doctors
  belongs_to :doctors
  has_many :treatments
  has_many :diets
  has_many :diagnosis
  has_many :appointments
  has_many :hospitalizations 

  
end

app/controllers/diagnoses_controller.rb
class DiagnosesController < InheritedResources::Base

  private

    def diagnosis_params
      params.require(:diagnosis).permit(:name, :type, :location, :stage, :user_id, :doctor_id)
    end

end

app/controllers/diets_controller.rb
class DietsController < InheritedResources::Base

  private

    def diet_params
      params.require(:diet).permit(:food, :drink, :exercise, :mental, :user_id, :doctor_id)
    end

end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController

 before_action :authenticate_user!, only: [:create, :update]

 


  private

  def Doctors_params
    params.require(:doctor).permit(:email,
                                 # :avatar,
                                 :first_name,
                                 :last_name,
                                 :street_address,
                                 :city,
                                 :zipcode,
                                 :country,
                                 :bio
                                )
  end

end

app/controllers/hospitalizations_controller.rb
class HospitalizationsController < InheritedResources::Base

  private

    def hospitalization_params
      params.require(:hospitalization).permit(:date, :admit, :discharge, :reasons)
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/treatments_controller.rb
class TreatmentsController < InheritedResources::Base

  private

    def treatment_params
      params.require(:treatment).permit(:name, :dosage, :schedule, :time, :user_id, :doctor_id)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

 before_action :authenticate_user!, only: [:create, :update]

 


  private

  def user_params
    params.require(:user).permit(:email,
                                 # :avatar,
                                 :first_name,
                                 :last_name,
                                 :street_address,
                                 :city,
                                 :zipcode,
                                 :country,
                                 :bio
                                )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/diagnoses_helper.rb
module DiagnosesHelper
end

app/helpers/diets_helper.rb
module DietsHelper
end

app/helpers/hospitalizations_helper.rb
module HospitalizationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/treatments_helper.rb
module TreatmentsHelper
end

app/views/hospitalizations/_form.html.erb
<%= form_with(model: hospitalization, local: true) do |form| %>
  <% if hospitalization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(hospitalization.errors.count, "error") %> prohibited this hospitalization from being saved:</h2>

      <ul>
      <% hospitalization.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date %>
    <%= form.text_field :date %>
  </div>

  <div class="field">
    <%= form.label :admit %>
    <%= form.text_field :admit %>
  </div>

  <div class="field">
    <%= form.label :discharge %>
    <%= form.text_field :discharge %>
  </div>

  <div class="field">
    <%= form.label :reasons %>
    <%= form.text_area :reasons %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/hospitalizations/edit.html.erb
<h1>Editing Hospitalization</h1>

<%= render 'form', hospitalization: @hospitalization %>

<%= link_to 'Show', @hospitalization %> |
<%= link_to 'Back', hospitalizations_path %>

app/views/hospitalizations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Hospitalizations</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Admit</th>
      <th>Discharge</th>
      <th>Reasons</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hospitalizations.each do |hospitalization| %>
      <tr>
        <td><%= hospitalization.date %></td>
        <td><%= hospitalization.admit %></td>
        <td><%= hospitalization.discharge %></td>
        <td><%= hospitalization.reasons %></td>
        <td><%= link_to 'Show', hospitalization %></td>
        <td><%= link_to 'Edit', edit_hospitalization_path(hospitalization) %></td>
        <td><%= link_to 'Destroy', hospitalization, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hospitalization', new_hospitalization_path %>

app/views/hospitalizations/new.html.erb
<h1>New Hospitalization</h1>

<%= render 'form', hospitalization: @hospitalization %>

<%= link_to 'Back', hospitalizations_path %>

app/views/hospitalizations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @hospitalization.date %>
</p>

<p>
  <strong>Admit:</strong>
  <%= @hospitalization.admit %>
</p>

<p>
  <strong>Discharge:</strong>
  <%= @hospitalization.discharge %>
</p>

<p>
  <strong>Reasons:</strong>
  <%= @hospitalization.reasons %>
</p>

<%= link_to 'Edit', edit_hospitalization_path(@hospitalization) %> |
<%= link_to 'Back', hospitalizations_path %>