config/routes.rb
Rails.application.routes.draw do
  resources :hospitalizations
  resources :treatments
  resources :appointments
  resources :diagnoses
  resources :diets
  devise_for :doctors
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  get 'pages/about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "pages#home"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :user
  belongs_to :doctor
end

app/models/diagnosis.rb
class Diagnosis < ApplicationRecord
  belongs_to :user
  belongs_to :doctor
end

app/models/diet.rb
class Diet < ApplicationRecord
  belongs_to :user
  belongs_to :doctor
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :users
  has_many :treatments
  has_many :diets
  has_many :diagnosis
  has_many :appointments
  has_many :hospitalizations 
    
end

app/models/hospitalization.rb
class Hospitalization < ApplicationRecord
	belongs_to :user
    belongs_to :doctor
end

app/models/treatment.rb
class Treatment < ApplicationRecord
  belongs_to :user
  belongs_to :doctor
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :doctors
  belongs_to :doctors
  has_many :treatments
  has_many :diets
  has_many :diagnosis
  has_many :appointments
  has_many :hospitalizations 

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/diagnoses_controller.rb
class DiagnosesController < InheritedResources::Base

  private

    def diagnosis_params
      params.require(:diagnosis).permit(:name, :type, :location, :stage, :user_id, :doctor_id)
    end

end

app/controllers/diets_controller.rb
class DietsController < InheritedResources::Base

  private

    def diet_params
      params.require(:diet).permit(:food, :drink, :exercise, :mental, :user_id, :doctor_id)
    end

end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController

 before_action :authenticate_user!, only: [:create, :update]

 


  private

  def Doctors_params
    params.require(:doctor).permit(:email,
                                 # :avatar,
                                 :first_name,
                                 :last_name,
                                 :street_address,
                                 :city,
                                 :zipcode,
                                 :country,
                                 :bio
                                )
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/treatments_controller.rb
class TreatmentsController < InheritedResources::Base

  private

    def treatment_params
      params.require(:treatment).permit(:name, :dosage, :schedule, :time, :user_id, :doctor_id)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

 before_action :authenticate_user!, only: [:create, :update]

 


  private

  def user_params
    params.require(:user).permit(:email,
                                 # :avatar,
                                 :first_name,
                                 :last_name,
                                 :street_address,
                                 :city,
                                 :zipcode,
                                 :country,
                                 :bio
                                )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/diagnoses_helper.rb
module DiagnosesHelper
end

app/helpers/diets_helper.rb
module DietsHelper
end

app/helpers/hospitalizations_helper.rb
module HospitalizationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/treatments_helper.rb
module TreatmentsHelper
end

app/views/diets/_form.html.erb
<%= form_with(model: diet, local: true) do |form| %>
  <% if diet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(diet.errors.count, "error") %> prohibited this diet from being saved:</h2>

      <ul>
      <% diet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :food %>
    <%= form.text_area :food %>
  </div>

  <div class="field">
    <%= form.label :drink %>
    <%= form.text_area :drink %>
  </div>

  <div class="field">
    <%= form.label :exercise %>
    <%= form.text_area :exercise %>
  </div>

  <div class="field">
    <%= form.label :mental %>
    <%= form.text_area :mental %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :doctor_id %>
    <%= form.text_field :doctor_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/diets/edit.html.erb
<h1>Editing Diet</h1>

<%= render 'form', diet: @diet %>

<%= link_to 'Show', @diet %> |
<%= link_to 'Back', diets_path %>

app/views/diets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Diets</h1>

<table>
  <thead>
    <tr>
      <th>Food</th>
      <th>Drink</th>
      <th>Exercise</th>
      <th>Mental</th>
      <th>User</th>
      <th>Doctor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @diets.each do |diet| %>
      <tr>
        <td><%= diet.food %></td>
        <td><%= diet.drink %></td>
        <td><%= diet.exercise %></td>
        <td><%= diet.mental %></td>
        <td><%= diet.user %></td>
        <td><%= diet.doctor %></td>
        <td><%= link_to 'Show', diet %></td>
        <td><%= link_to 'Edit', edit_diet_path(diet) %></td>
        <td><%= link_to 'Destroy', diet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Diet', new_diet_path %>

app/views/diets/new.html.erb
<h1>New Diet</h1>

<%= render 'form', diet: @diet %>

<%= link_to 'Back', diets_path %>

app/views/diets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Food:</strong>
  <%= @diet.food %>
</p>

<p>
  <strong>Drink:</strong>
  <%= @diet.drink %>
</p>

<p>
  <strong>Exercise:</strong>
  <%= @diet.exercise %>
</p>

<p>
  <strong>Mental:</strong>
  <%= @diet.mental %>
</p>

<p>
  <strong>User:</strong>
  <%= @diet.user %>
</p>

<p>
  <strong>Doctor:</strong>
  <%= @diet.doctor %>
</p>

<%= link_to 'Edit', edit_diet_path(@diet) %> |
<%= link_to 'Back', diets_path %>

app/views/treatments/_form.html.erb
<%= form_with(model: treatment, local: true) do |form| %>
  <% if treatment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(treatment.errors.count, "error") %> prohibited this treatment from being saved:</h2>

      <ul>
      <% treatment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :dosage %>
    <%= form.text_field :dosage %>
  </div>

  <div class="field">
    <%= form.label :schedule %>
    <%= form.text_area :schedule %>
  </div>

  <div class="field">
    <%= form.label :time %>
    <%= form.text_area :time %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :doctor_id %>
    <%= form.text_field :doctor_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/treatments/edit.html.erb
<h1>Editing Treatment</h1>

<%= render 'form', treatment: @treatment %>

<%= link_to 'Show', @treatment %> |
<%= link_to 'Back', treatments_path %>

app/views/treatments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Treatments</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Dosage</th>
      <th>Schedule</th>
      <th>Time</th>
      <th>User</th>
      <th>Doctor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @treatments.each do |treatment| %>
      <tr>
        <td><%= treatment.name %></td>
        <td><%= treatment.dosage %></td>
        <td><%= treatment.schedule %></td>
        <td><%= treatment.time %></td>
        <td><%= treatment.user %></td>
        <td><%= treatment.doctor %></td>
        <td><%= link_to 'Show', treatment %></td>
        <td><%= link_to 'Edit', edit_treatment_path(treatment) %></td>
        <td><%= link_to 'Destroy', treatment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Treatment', new_treatment_path %>

app/views/treatments/new.html.erb
<h1>New Treatment</h1>

<%= render 'form', treatment: @treatment %>

<%= link_to 'Back', treatments_path %>

app/views/treatments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @treatment.name %>
</p>

<p>
  <strong>Dosage:</strong>
  <%= @treatment.dosage %>
</p>

<p>
  <strong>Schedule:</strong>
  <%= @treatment.schedule %>
</p>

<p>
  <strong>Time:</strong>
  <%= @treatment.time %>
</p>

<p>
  <strong>User:</strong>
  <%= @treatment.user %>
</p>

<p>
  <strong>Doctor:</strong>
  <%= @treatment.doctor %>
</p>

<%= link_to 'Edit', edit_treatment_path(@treatment) %> |
<%= link_to 'Back', treatments_path %>